### PR TITLE
Remove camlp4 and update

### PR DESCRIPTION
**Pull request by mor1**
Finally updating mirage-decks, including moving away from camlp4.
~~Not ready for merge yet.~~

### CODE REVIEW

**Comment by yomimono** [comment]
I see you have "not done" in the commit messages still -- what's left to do here?  I haven't looked closely at the changes but I see that your tests are passing, which seems like a good sign.  Thanks for your work on this!

**Comment by mor1** [comment]
When I last tested it, I think I'd botched something in the conversion so pages weren't rendering quite right. Should finish it off in the next week.

--  
Cheers,

R.

**Comment by mor1** [comment]
Ok, I think that works now. Only light testing but the two topmost decks appear to be ok and that tests the index and both Reveal 2.4.0 and Reveal 2.6.2 which is basically everything.

If Travis passes I think this is ready for merge -- look ok to you @yomimono @avsm?

**Comment by yomimono** [comment]
This is great!  Thanks very much, @mor1 . :)

**Comment by yomimono** [comment]
What do we need to do to rebuild http://decks.openmirage.org/ ?

**Comment by mor1** [comment]
The site *ought* to rebuild as part of Travis completing testing the merge result successfully.
It should then reboot due to the post-merge hook in the deployment repo.
I'll check shortly...

**Comment by mor1** [comment]
Hm, Travis has failed the `DEPLOY=1` build -- looks like the name of the output `.xen` file changed. Will look into it.

**Pull request merged**
