### PR TITLE
Port OUPS slides to reveal.js

### PR DESCRIPTION
**Pull request by samoht**
The more times goes, the more I dislike that reveal.js stuff :p 

I've started hacked quickly a pandoc -> mirage-deck translator though, but that's not ready yet.

### CODE REVIEW

**Comment by avsm** [comment]
Thx! Go ahead and merge so it pushes to deployment

**Comment by mor1** [comment]
(any particular things you dislike about reveal.js? might be hackable...)

On 22 January 2015 at 12:06, Thomas Gazagnaire <notifications@github.com>
wrote:

> Merged #37 <https://github.com/mirage/mirage-decks/pull/37>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage-decks/pull/37#event-222967200>.
>



-- 
Richard Mortier
mort@cantab.net

**Comment by samoht** [comment]
random rants:
- cannot read pdf images (need to convert to .pdf) and need to use HTML and not markdown to include them
- need to put double space to separate slides (in pandoc markdown, `##` is enough to create a new slide)
- the title fonts is too big so need to shorten the title

general impression is that font is too big and clumsy, but I  can leave with that :p `pandoc` has an option to convert markdown pandoc to revealjs, I think that could be integrated with mirage-decks workflow (https://gist.github.com/aaronwolen/5017084)

**Comment by mor1** [comment]
ok-- sounds like two things: integrate pandoc into workflow (ocaml not
functional enough? use haskell! ;)  and fix the stylesheet (easy if
tedious).

we probably want to have a stylesheet that's not horizon.css at some point
anyway... (assuming that's the one you've been using)

On 22 January 2015 at 14:49, Thomas Gazagnaire <notifications@github.com>
wrote:

> random rants:
>
>    - cannot read pdf images (need to convert to .pdf) and need to use
>    HTML and not markdown to include them
>    - need to put double space to separate slides (in pandoc markdown, ##
>    is enough to create a new slide)
>    - the title fonts is too big so need to shorten the title
>
> general impression is that font is too big and clumsy, but I can leave
> with that :p pandoc has an option to convert markdown pandoc to revealjs,
> I think that could be integrated with mirage-decks workflow (
> https://gist.github.com/aaronwolen/5017084)
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage-decks/pull/37#issuecomment-71030912>.
>



-- 
Richard Mortier
mort@cantab.net

**Pull request merged**
