### PR TITLE
Add all my slide decks (do not merge)

### PR DESCRIPTION
**Pull request by amirmc**
This is towards closing #49

I have another dozen or so slide decks to push to this branch so this PR is for early feedback (in case I need to edit the PDFs or put them elsewhere).

Thanks to @mor1 for pointing me at the snippet for embedding PDFs!

Slides to add:
- [x] PolyConf 2015
- [x] IoT Summit 2015
- [x] ProductCamp London 2015
- [ ] BP Security 2015
- [ ] Cambridge Skeptics 2014
- [ ] Digital Conversations 2014
- [ ] BT-Insights 2014
- [ ] Smart Homes 2013
- [ ] Data Insights 2013
- [ ] Darwin Seminar 2013
- [ ] BT-Insights 2013

### CODE REVIEW

**Comment by amirmc** [comment]
These are the decks from 2015.  Travis keeps timing out on the Xen build.

Once it's green, I'll merge these. Will submit a separate PR for older slides.

**Comment by amirmc** [comment]
This takes ~9mins to build on my (reasonably fast) machine. It's timing out on Travis. Not sure that adding PDFs to the repo is the way to go.

**Comment by mor1** [comment]
Change storage backend to fat rather than crunch. But then need to sort out
how the fat image is mounted on deployment.

**Comment by samoht** [comment]
@mor1 there are some example [here](https://github.com/mirage/mirage-www-deployment/blob/master/scripts/deploy-tls.sh#L46-51). Need to include the script to build the FAT image and the contents of the FAT file somewhere on the server though.

**Comment by samoht** [comment]
An other possibility is to beta-test the Irmin/Mirage integration: https://github.com/mirage/mirage-dev/pull/56 I'll merge the branch shortly into mirage-dev.

**Comment by mor1** [comment]
@amirmc Just checking back through PRs and noticed this one languishing :) Do you have any current plans to complete this, or should I just merge what's there so far, or should I just close it?

**Comment by amirmc** [comment]
Ugh, I'd totally forgotten about this. Thanks for the reminder, @mor1.  I don't have current plans to add more to this so please do merge/close as you see fit.  Thanks for looking over the PRs! :)

**Comment by mor1** [comment]
Looks like some bitrot in the meantime -- I'll merge and then fix up. Thanks!

**Comment by mor1** [comment]
Ok done via command line. Closing this.

**Pull request closed without merging**
